disabled_rules:
  - nesting
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length:
  warning: 140
type_body_length:
  warning: 300
file_length:
  warning: 500
type_name:
  min_length: 4 # warning
  max_length: 40 # warning
identifier_name:
  min_length: 3 # warning
  excluded:
    - id
