disabled_rules:
  - nesting
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - anyobject_protocol
  - convenience_type
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length:
  warning: 140
type_body_length:
  warning: 300
file_length:
  warning: 500
type_name:
  min_length: 4 # warning
  max_length: 40 # warning
identifier_name:
  min_length: 3 # warning
  excluded:
    - id
